// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRORBDFBMTc-pj6xe_RAXRFP-DkhMZMOc',
    appId: '1:17028746781:android:82cdccc984b9ac978fc0f4',
    messagingSenderId: '17028746781',
    projectId: 'bansachappflutter',
    databaseURL: 'https://bansachappflutter-default-rtdb.firebaseio.com',
    storageBucket: 'bansachappflutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdqXzdyUhUDk9GuDI7Mfw_Cp2ct0peIL4',
    appId: '1:17028746781:ios:2c24a29bfcf201e58fc0f4',
    messagingSenderId: '17028746781',
    projectId: 'bansachappflutter',
    databaseURL: 'https://bansachappflutter-default-rtdb.firebaseio.com',
    storageBucket: 'bansachappflutter.firebasestorage.app',
    androidClientId: '17028746781-6vja38487dohlpi16gvtjtlt9tlvd1kp.apps.googleusercontent.com',
    iosClientId: '17028746781-11i2qt9dimaq4en4ohvbi12u381rtjhf.apps.googleusercontent.com',
    iosBundleId: 'com.example.appBanSach',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdqXzdyUhUDk9GuDI7Mfw_Cp2ct0peIL4',
    appId: '1:17028746781:ios:2c24a29bfcf201e58fc0f4',
    messagingSenderId: '17028746781',
    projectId: 'bansachappflutter',
    databaseURL: 'https://bansachappflutter-default-rtdb.firebaseio.com',
    storageBucket: 'bansachappflutter.firebasestorage.app',
    androidClientId: '17028746781-6vja38487dohlpi16gvtjtlt9tlvd1kp.apps.googleusercontent.com',
    iosClientId: '17028746781-11i2qt9dimaq4en4ohvbi12u381rtjhf.apps.googleusercontent.com',
    iosBundleId: 'com.example.appBanSach',
  );
}
